### ISSUE TITLE
Strand specificity in fasta retrieval

### ISSUE THREAD

**Issue by MatthewRalston** [jmjuanes/bedjs#1]
Hello,
I had a question about your [fasta sequence retrieval method](https://github.com/jmjuanes/bedjs/blob/master/lib/fasta.js#L136). In this function, you read bytes into a new buffer, parse the buffer, and then if the global options object for the fetching method contains `{strand: true}`, then you automatically take the complementary sequence instead of checking the strand specificity of the BED object first to see if it is forward or reverse... am i missing something?

It seems that if strand specificity is set to true, you would read the sequence from the chromosome in the orientation specified by the BED record. Thus, if the BED record has forward strand specified, and you took the reverse complement a la [`fasta.jsL136`](https://github.com/jmjuanes/bedjs/blob/master/lib/fasta.js#L136) then that would produce an incorrect sequence.

Thanks for your work!

**Comment by jmjuanes** [comment]
Hello @MatthewRalston , thanks for your issue!

You are right, if the BED record has forward strand and the options contains `{ strand: true }`, it will generate the reverse complement. Oops, this is incorrect, I am going to fix it right now. 

Thanks a lot! :smile:

**Comment by jmjuanes** [comment]
Hello again,

I have updated the package and I think that now it works as expected. Can you try it?

Thanks! :smile:

**Comment by MatthewRalston** [comment]
Gracias! que alivio.
